export const htmlcssnavitems = [
  {
    name: "HTML",
    tutorial: true,
    ref: true,
  },
  {
    name: "CSS",
    tutorial: true,
    ref: true,
  },
  {
    name: "RWD",
    tutorial: true,
    ref: false,
  },
  {
    name: "Bootstrap",
    tutorial: false,
    ref: true,
    overview: true,
  },
  {
    name: "W3.CSS",
    tutorial: true,
    ref: true,
  },
  {
    name: "SASS",
    tutorial: true,
    ref: true,
  },
  {
    name: "Colors",
    tutorial: true,
    ref: true,
  },
  {
    name: "Icons",
    tutorial: true,
    ref: true,
  },
  {
    name: "SVG",
    tutorial: true,
    ref: true,
  },
  {
    name: "Canvas",
    tutorial: true,
    ref: true,
  },
  {
    name: "Graphics",
    tutorial: true,
    ref: false,
  },
];

export const jsitems = [
  {
    name: "JavaScript",
    tutorial: true,
    ref: true,
  },
  {
    name: "React",
    tutorial: true,
    ref: false,
  },
  {
    name: "jQuery",
    tutorial: true,
    ref: true,
  },
  {
    name: "Vue",
    tutorial: true,
    ref: true,
  },
  {
    name: "Angular JS",
    tutorial: true,
    ref: true,
  },
  {
    name: "JSON",
    tutorial: true,
    ref: true,
  },
  {
    name: "AJAX",
    tutorial: true,
    ref: false,
  },
  {
    name: "W3.JS",
    tutorial: true,
    ref: true,
  },
  {
    name: "AppML",
    tutorial: true,
    ref: true,
  },
];

export const backenditems = [
  {
    name: "Python",
    tutorial: true,
    ref: true,
  },
  {
    name: "SQL",
    tutorial: true,
    ref: false,
  },
  {
    name: "MySQL",
    tutorial: true,
    ref: true,
  },
  {
    name: "PHP",
    tutorial: true,
    ref: true,
  },
  {
    name: "JAVA",
    tutorial: true,
    ref: true,
  },
  {
    name: "C",
    tutorial: true,
    ref: false,
  },
  {
    name: "C++",
    tutorial: true,
    ref: false,
  },
  {
    name: "C#",
    tutorial: true,
    ref: false,
  },
  {
    name: "R",
    tutorial: true,
    ref: false,
  },
  {
    name: "Kotlin",
    tutorial: true,
    ref: false,
  },
  {
    name: "Go",
    tutorial: true,
    ref: false,
  },
  {
    name: "JSON",
    tutorial: true,
    ref: true,
  },
  {
    name: "Django",
    tutorial: true,
    ref: true,
  },
  {
    name: "PostgreSQL",
    tutorial: true,
    ref: true,
  },
  {
    name: "TypeScript",
    tutorial: true,
    ref: true,
  },
  {
    name: "ASP",
    tutorial: true,
    ref: true,
  },
  {
    name: "Node.js",
    tutorial: true,
    ref: true,
  },
  {
    name: "RaspberryPi",
    tutorial: true,
    ref: false,
  },
  {
    name: "Git",
    tutorial: true,
    ref: false,
  },
  {
    name: "MongoDB",
    tutorial: true,
    ref: false,
  },
  {
    name: "AWS",
    tutorial: true,
    ref: false,
  },
  {
    name: "XML",
    tutorial: true,
    ref: true,
  },
];

export const backendCertified = [
  {
    name: "Python",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "SQL",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "MySQL",
    certificate: true,
    course: false,
    bootcamp: false,
  },
  {
    name: "PHP",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "JAVA",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "C",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "C++",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "C#",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "R",
    certificate: true,
    course: false,
    bootcamp: false,
  },
  {
    name: "Django",
    certificate: true,
    course: false,
    bootcamp: false,
  },
  {
    name: "TypeScript",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "XML",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Cyber Security",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Accessibility",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Python Apps on AWS",
    certificate: false,
    course: true,
    bootcamp: false,
  },

  {
    name: "AWS Training",
    certificate: false,
    course: true,
    bootcamp: false,
  },
];

export const dataitems = [
  {
    name: "AI",
    tutorial: true,
  },
  {
    name: "Generative AI",
    tutorial: true,
  },
  {
    name: "ChatGPT-3.5",
    tutorial: true,
  },
  {
    name: "ChatGPT-4",
    tutorial: true,
  },
  {
    name: "Google Bard",
    tutorial: true,
  },
  {
    name: "Machine Learning",
    tutorial: true,
  },
  {
    name: "NumPy",
    tutorial: true,
  },
  {
    name: "Pandas",
    tutorial: true,
  },
  {
    name: "SciPy",
    tutorial: true,
  },
  {
    name: "Matplotlib",
    tutorial: true,
  },
  {
    name: "Statistics",
    tutorial: true,
  },
  {
    name: "Exel",
    tutorial: true,
  },
  {
    name: "Google Sheets",
    tutorial: true,
  },
];

export const webitems = [
  { name: "Create a Website ", hot: true },
  { name: "Create a Server", new: true },
  { name: "Where To Start" },
  { name: "Web Templates" },
  { name: "Web Statistics" },
  { name: "Web Certificates" },
  { name: "Web Development" },
  { name: "Code Editor" },
  { name: "Test Your Typing Speed" },
  { name: "Play a Code Game" },
  { name: "Cyber Security" },
  { name: "Accessibility" },
  { name: "Join our Newsletter" },
];

export const htmlcssexercises = [
  {
    name: "HTML",
    exercise: true,
    quiz: true,
  },
  {
    name: "CSS",
    exercise: true,
    quiz: true,
  },
  {
    name: "Bootstrap",
    exercise: true,
    quiz: true,
  },
];

export const htmlcsscertified = [
  {
    name: "HTML",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "CSS",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "Bootstrap",
    certificate: true,
    course: true,
    bootcamp: false,
  },
];

export const jsexercises = [
  {
    name: "JavaScript",
    exercise: true,
    quiz: true,
  },
  {
    name: "React",
    exercise: true,
    quiz: true,
  },
  {
    name: "jQuery",
    exercise: true,
    quiz: true,
  },
  {
    name: "Vue",
    exercise: true,
    quiz: true,
  },
];

export const jscertified = [
  {
    name: "JavaScript",
    certificate: true,
    course: true,
    bootcamp: true,
  },
  {
    name: "React",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "jQuery",
    certificate: true,
    course: true,
    bootcamp: false,
  },
  {
    name: "Vue",
    certificate: true,
    course: false,
    bootcamp: false,
  },
];

export const dataexercises = [
  {
    name: "NumPy",
    exercise: true,
    quiz: true,
  },
  {
    name: "Pandas",
    exercise: true,
    quiz: true,
  },
  {
    name: "SciPy",
    exercise: true,
    quiz: true,
  },
  {
    name: "Exel",
    exercise: true,
    quiz: false,
  },
];

export const programs = [
  {
    name: "Full Acess",
    bestValue: true,
    certificate: false,
    course: false,
  },

  {
    name: "Front End",
    bestValue: false,
    certificate: true,
    course: true,
  },
  {
    name: "Web Dev.",
    bestValue: false,
    certificate: true,
    course: true,
  },
  {
    name: "Web Design",
    bestValue: false,
    certificate: true,
    course: true,
  },
];

export const leftSidebarItems1 = [
  "HTML HOME",
  "HTML Introduction",
  "HTML Editors",
  "HTML Basic",
  "HTML Elements",
  "HTML Attributes",
  "HTML Headings",
  "HTML Paragraphs",
  "HTML Styles",
  "HTML Formatting",
  "HTML Quotations",
  "HTML Comments",
  "HTML Colors",
  "HTML CSS",
  "HTML Links",
  "HTML Images",
  "HTML Favicon",
  "HTML Page Title",
  "HTML Tables",
  "HTML Lists",
  "HTML Block & Inline",
  "HTML Classes",
  "HTML Id",
  "HTML Iframes",
  "HTML JavaScript",
  "HTML File Paths",
  "HTML Head",
  "HTML Layout",
  "HTML Responsive",
  "HTML Computercode",
  "HTML Semantics",
  "HTML Style Guide",
  "HTML Entities",
  "HTML Symbols",
  "HTML Emojis",
  "HTML Charset",
  "HTML URL Encode",
  "HTML vs. XHTML",
];

export const leftSidebarItems2 = [
  "HTML Forms",
  "HTML Form Attributes",
  "HTML Form Elements",
  "HTML Input Types",
  "HTML Input Attributes",
  "HTML Input Form Attributes",
];

export const leftSidebarItems3 = [
  "HTML Tag List",
  "HTML Attributes",
  "HTML Global Attributes",
  "HTML Browser Support",
  "HTML Events",
  "HTML Colors",
  "HTML Canvas",
  "HTML Audio/Video",
  "HTML Doctypes",
  "HTML Character Sets",
  "HTML URL Encode",
  "HTML Lang Codes",
  "HTTP Messages",
  "HTTP Methods",
  "PX to EM Converter",
  "Keyboard Shortcuts",
];

export const htmlReferences = [
  "HTML Elements",
  "Browser Support",
  "Attributes",
  "Global Attributes",
  "Event Attributes",
  "Color Names",
  "Canvas",
  "Audio/Video DOM",
  "Character Sets",
  "URL Encoding",
  "Language Codes",
  "Country Codes",
  "HTTP Messages",
  "Px to Em Converter",
  "Keyboard Shortcuts",
];

export const cssleftsidebaritems1 = [
  "CSS HOME",
  "CSS Introduction",
  "CSS Syntax",
  "CSS Selectors",
  "CSS How To",
  "CSS Comments",
  "CSS Colors",
  "CSS Backgrounds",
  "CSS Borders",
  "CSS Margins",
  "CSS Padding",
  "CSS Height/Width",
  "CSS Box Model",
  "CSS Outline",
  "CSS Text",
  "CSS Fonts",
  "CSS Icons",
  "CSS Links",
  "CSS Lists",
  "CSS Tables",
  "CSS Display",
  "CSS Max-width",
  "CSS Position",
  "CSS Z-index",
  "CSS Overflow",
  "CSS Float",
  "CSS Inline-block",
  "CSS Align",
  "CSS Combinators",
  "CSS Pseudo-class",
  "CSS Pseudo-element",
  "CSS Opacity",
  "CSS Navigation Bar",
  "CSS Dropdowns",
  "CSS Image Gallery",
  "CSS Image Sprites",
  "CSS Attr Selectors",
  "CSS Forms",
  "CSS Counters",
  "CSS Website Layout",
  "CSS Units",
  "CSS Specificity",
  "CSS !important",
  "CSS Math Functions",
];

export const cssleftsidebaritems2 = [
  "CSS Rounded Corners",
  "CSS Border Images",
  "CSS Backgrounds",
  "CSS Colors",
  "CSS Color Keywords",
  "CSS Gradients",
  "CSS Shadows",
  "CSS Text Effects",
  "CSS Web Fonts",
  "CSS 2D Transforms",
  "CSS 3D Transforms",
  "CSS Transitions",
  "CSS Animations",
  "CSS Tooltips",
  "CSS Style Images",
  "CSS Image Reflection",
  "CSS object-fit",
  "CSS object-position",
  "CSS Masking",
  "CSS Buttons",
  "CSS Pagination",
  "CSS Multiple Columns",
  "CSS User Interface",
  "CSS Variables",
  "CSS Box Sizing",
  "CSS Media Queries",
  "CSS MQ Examples",
  "CSS Flexbox",
];

export const cssleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "CSS Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "CSS SASS",
  "SASS Tutorial",
  "CSS Examples",
  "CSS Templates",
  "CSS Examples",
  "CSS Editor",
  "CSS Snippets",
  "CSS Quiz",
  "CSS Exercises",
  "CSS Bootcamp",
  "CSS Certificate",
  "CSS References",
  "CSS Reference",
  "CSS Selectors",
  "CSS Functions",
  "CSS Reference Aural",
  "CSS Web Safe Fonts",
  "CSS Animatable",
  "CSS Units",
  "CSS PX-EM Converter",
  "CSS Colors",
  "CSS Color Values",
  "CSS Default Values",
  "CSS Browser Support",
];

export const cssreferences = [
  "CSS Properties",
  "CSS Selectors",
  "CSS Browser Support",
  "CSS Functions",
  "CSS Animatable",
  "CSS Aural",
  "CSS Web Safe Fonts",
  "CSS Units",
  "Px to Em Conversion",
  "CSS Colors",
  "CSS Default Values",
  "CSS Entities",
];

export const jsleftsidebaritems1 = [
  "JS HOME",
  "JS Introduction",
  "JS Where To",
  "JS Output",
  "JS Statements",
  "JS Syntax",
  "JS Comments",
  "JS Variables",
  "JS Let",
  "JS Const",
  "JS Operators",
  "JS Arithmetic",
  "JS Assignment",
  "JS Data Types",
  "JS Functions",
  "JS Objects",
  "JS Events",
  "JS Strings",
  "JS String Methods",
  "JS String Search",
  "JS String Templates",
  "JS Numbers",
  "JS BigInt",
  "JS Number Methods",
  "JS Number Properties",
  "JS Arrays",
  "JS Array Methods",
  "JS Array Sort",
  "JS Array Iteration",
  "JS Array Const",
  "JS Dates",
  "JS Date Formats",
  "JS Date Get Methods",
  "JS Date Set Methods",
  "JS Math",
  "JS Random",
  "JS Booleans",
  "JS Comparisons",
  "JS If Else",
  "JS Switch",
  "JS Loop For",
  "JS Loop For In",
  "JS Loop For Of",
  "JS Loop While",
  "JS Break",
  "JS Iterables",
  "JS Sets",
  "JS Maps",
  "JS Typeof",
  "JS Type Conversion",
  "JS Bitwise",
  "JS RegExp",
  "JS Precedence",
  "JS Errors",
  "JS Scope",
  "JS Hoisting",
  "JS Strict Mode",
  "JS this Keyword",
  "JS Arrow Function",
  "JS Classes",
  "JS Modules",
  "JS JSON",
  "JS Debugging",
  "JS Style Guide",
  "JS Best Practices",
  "JS Mistakes",
  "JS Performance",
  "JS Reserved Words",
];

export const jsleftsidebaritems2 = [
  "DOM Intro",
  "DOM Methods",
  "DOM Document",
  "DOM Elements",
  "DOM HTML",
  "DOM Forms",
  "DOM CSS",
  "DOM Animations",
  "DOM Events",
  "DOM Event Listener",
  "DOM Navigation",
  "DOM Nodes",
  "DOM Collections",
  "DOM Node Lists",
];

export const jsleftsidebaritems3 = [
  "JS Window",
  "JS Screen",
  "JS Location",
  "JS History",
  "JS Navigator",
  "JS Popup Alert",
  "JS Timing",
  "JS Cookies",
  "JS Web APIs",
  "Web API Intro",
  "Web Forms API",
  "Web History API",
  "Web Storage API",
  "Web Worker API",
  "Web Fetch API",
  "Web Geolocation API",
  "JS AJAX",
  "AJAX Intro",
  "AJAX XMLHttp",
  "AJAX Request",
  "AJAX Response",
  "AJAX XML File",
  "AJAX PHP",
  "AJAX ASP",
  "AJAX Database",
  "AJAX Applications",
  "AJAX Examples",
  "JS JSON",
  "JSON Intro",
  "JSON Syntax",
  "JSON vs XML",
  "JSON Data Types",
  "JSON Parse",
  "JSON Stringify",
  "JSON Objects",
  "JSON Arrays",
  "JSON Server",
  "JSON PHP",
  "JSON HTML",
  "JSON JSONP",
];

export const sqlleftsidebaritems1 = [
  "SQL Intro",
  "SQL Syntax",
  "SQL Select",
  "SQL Select Distinct",
  "SQL Where",
  "SQL Order By",
  "SQL And",
  "SQL Or",
  "SQL Not",
  "SQL Insert Into",
  "SQL Null Values",
  "SQL Update",
  "SQL Delete",
  "SQL Select Top",
  "SQL Min and Max",
  "SQL Count",
  "SQL Sum",
  "SQL Avg",
  "SQL Like",
  "SQL Wildcards",
  "SQL In",
  "SQL Between",
  "SQL Aliases",
  "SQL Joins",
  "SQL Inner Join",
  "SQL Left Join",
  "SQL Right Join",
  "SQL Full Join",
  "SQL Self Join",
  "SQL Union",
  "SQL Group By",
  "SQL Having",
  "SQL Exists",
  "SQL Any, All",
  "SQL Select Into",
  "SQL Insert Into Select",
  "SQL Case",
  "SQL Null Functions",
  "SQL Stored Procedures",
  "SQL Comments",
  "SQL Operators",
];

export const sqlleftsidebaritems2 = [
  "SQL Create DB",
  "SQL Drop DB",
  "SQL Backup DB",
  "SQL Create Table",
  "SQL Drop Table",
  "SQL Alter Table",
  "SQL Constraints",
  "SQL Not Null",
  "SQL Unique",
  "SQL Primary Key",
  "SQL Foreign Key",
  "SQL Check",
  "SQL Default",
  "SQL Index",
  "SQL Auto Increment",
  "SQL Dates",
  "SQL Views",
  "SQL Injection",
  "SQL Hosting",
  "SQL Data Types",
];

export const sqlleftsidebaritems3 = [
  "SQL Keywords",
  "MySQL Functions",
  "SQL Server Functions",
  "MS Access Functions",
  "SQL Quick Ref",
  "SQL Examples",
  "SQL Examples",
  "SQL Editor",
  "SQL Quiz",
  "SQL Exercises",
  "SQL Bootcamp",
  "SQL Certificate",
];

export const sqlreferences = [
  "SQL Keyword Reference",

  "MYSQL Functions",

  "SQLServer Functions",

  "MS Access Functions",

  "SQL Quick Reference",
];

export const pythonleftsidebaritems1 = [
  "PYTHON HOME",
  "PYTHON Introduction",
  "PYTHON Syntax",
  "PYTHON Selectors",
  "PYTHON How To",
  "PYTHON Comments",
  "PYTHON Colors",
  "PYTHON Backgrounds",
  "PYTHON Borders",
  "PYTHON Margins",
  "PYTHON Padding",
  "PYTHON Height/Width",
  "PYTHON Box Model",
  "PYTHON Outline",
  "PYTHON Text",
  "PYTHON Fonts",
  "PYTHON Icons",
  "PYTHON Links",
  "PYTHON Lists",
  "PYTHON Tables",
  "PYTHON Display",
  "PYTHON Max-width",
  "PYTHON Position",
  "PYTHON Z-index",
  "PYTHON Overflow",
  "PYTHON Float",
  "PYTHON Inline-block",
  "PYTHON Align",
  "PYTHON Combinators",
  "PYTHON Pseudo-class",
  "PYTHON Pseudo-element",
  "PYTHON Opacity",
  "PYTHON Navigation Bar",
  "PYTHON Dropdowns",
  "PYTHON Image Gallery",
  "PYTHON Image Sprites",
  "PYTHON Attr Selectors",
  "PYTHON Forms",
  "PYTHON Counters",
  "PYTHON Website Layout",
  "PYTHON Units",
  "PYTHON Specificity",
  "PYTHON !important",
  "PYTHON Math Functions",
];

export const pythonleftsidebaritems2 = [
  "PYTHON Border Images",
  "PYTHON Backgrounds",
  "PYTHON Colors",
  "PYTHON Color Keywords",
  "PYTHON Gradients",
  "PYTHON Shadows",
  "PYTHON Text Effects",
  "PYTHON Web Fonts",
  "PYTHON 2D Transforms",
  "PYTHON 3D Transforms",
  "PYTHON Transitions",
  "PYTHON Rounded Corners",
  "PYTHON Animations",
  "PYTHON Tooltips",
  "PYTHON Style Images",
  "PYTHON Image Reflection",
  "PYTHON object-fit",
  "PYTHON object-position",
  "PYTHON Masking",
  "PYTHON Buttons",
  "PYTHON Pagination",
  "PYTHON Multiple Columns",
  "PYTHON User Interface",
  "PYTHON Variables",
  "PYTHON Box Sizing",
  "PYTHON Media Queries",
  "PYTHON MQ Examples",
  "PYTHON Flexbox",
];

export const pythonleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "CSS Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "PYTHON SASS",
  "PYTHON Tutorial",
  "PYTHONExamples",
  "PYTHONTemplates",
  "PYTHONExamples",
  "PYTHONEditor",
  "PYTHON Snippets",
  "PYTHON Quiz",
  "PYTHON Exercises",
  "PYTHON Bootcamp",
  "PYTHON Certificate",
  "PYTHON References",
  "PYTHON Reference",
  "PYTHON Selectors",
  "PYTHON Functions",
  "PYTHON Reference Aural",
  "PYTHONWeb Safe Fonts",
  "PYTHONAnimatable",
  "PYTHON Units",
  "PYTHONPX-EM Converter",
  "PYTHON Colors",
  "PYTHON Color Values",
  "PYTHON Default Values",
  "PYTHON Browser Support",
];

export const pythonreferences = [
  "PYTHON Properties",
  "PYTHON Selectors",
  "PYTHON Browser Support",
  "PYTHON Functions",
  "PYTHON Animatable",
  "PYTHON Aural",
  "PYTHON Web Safe Fonts",
  "PYTHON Units",
  "PYTHON Colors",
  "PYTHON Default Values",
  "PYTHON Entities",
];

export const javaleftsidebaritems1 = [
  "JAVA  HOME",
  "JAVA  Introduction",
  "JAVA  Syntax",
  "JAVA  Selectors",
  "JAVA How To",
  "JAVA Comments",
  "JAVA  Colors",
  "JAVA  Backgrounds",
  "JAVA  Borders",
  "JAVA  Margins",
  "JAVA  Padding",
  "JAVA  Height/Width",
  "JAVA  Box Model",
  "JAVA  Outline",
  "JAVA  Text",
  "JAVA  Fonts",
  "JAVA  Icons",
  "JAVA  Links",
  "JAVA  Lists",
  "JAVA  Tables",
  "JAVA  Display",
  "JAVA  Max-width",
  "JAVA Position",
  "JAVA  Z-index",
  "JAVA  Overflow",
  "JAVA  Float",
  "JAVA  Inline-block",
  "JAVA  Align",
  "JAVA  Combinators",
  "JAVA  Pseudo-class",
  "JAVA  Pseudo-element",
  "JAVA  Opacity",
  "JAVA  Navigation Bar",
  "JAVA  Dropdowns",
  "JAVA  Image Gallery",
  "JAVA  Image Sprites",
  "JAVA  Attr Selectors",
  "JAVA  Forms",
  "PJAVA Counters",
  "JAVA  Website Layout",
  "JAVA  Units",
  "JAVA  Specificity",
  "JAVA  !important",
  "JAVA  Math Functions",
];

export const javaleftsidebaritems2 = [
  "JAVA Border Images",
  "JAVA Backgrounds",
  "JAVA Colors",
  "JAVA Color Keywords",
  "JAVA Gradients",
  "JAVA Shadows",
  "JAVA Text Effects",
  "JAVA Web Fonts",
  "JAVA 2D Transforms",
  "JAVA 3D Transforms",
  "JAVA Transitions",
  "JAVA Rounded Corners",
  "JAVA Animations",
  "JAVA Tooltips",
  "JAVA Style Images",
  "JAVA Image Reflection",
  "JAVA object-fit",
  "JAVA object-position",
  "JAVA Masking",
  "JAVA Buttons",
  "JAVA Pagination",
  "JAVA Multiple Columns",
  "JAVA User Interface",
  "JAVA Variables",
  "JAVA Box Sizing",
  "JAVA Media Queries",
  "JAVA MQ Examples",
  "JAVA Flexbox",
];

export const javaleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "JAVA Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "JAVA SASS",
  "JAVA Tutorial",
  "JAVAExamples",
  "JAVATemplates",
  "JAVAExamples",
  "JAVAEditor",
  "JAVA Snippets",
  "JAVA Quiz",
  "JAVA Exercises",
  "JAVA Bootcamp",
  "JAVA Certificate",
  "JAVA References",
  "JAVA Reference",
  "JAVA Selectors",
  "JAVA Functions",
  "JAVA Reference Aural",
  "JAVAWeb Safe Fonts",
  "JAVAAnimatable",
  "JAVA Units",
  "JAVAPX-EM Converter",
  "JAVA Colors",
  "JAVA Color Values",
  "JAVA Default Values",
  "JAVA Browser Support",
];

export const javareferences = [
  "JAVA Properties",
  "JAVA Selectors",
  "JAVA Browser Support",
  "JAVA Functions",
  "JAVA Animatable",
  "JAVA Aural",
  "JAVA Web Safe Fonts",
  "JAVA Units",
  "JAVA Colors",
  "JAVA Default Values",
  "JAVA Entities",
];

export const cleftsidebaritems1 = [
  "C   HOME",
  "C   Introduction",
  "C   Syntax",
  "C   Selectors",
  "C  How To",
  "C  Comments",
  "C   Colors",
  "C   Backgrounds",
  "C   Borders",
  "C   Margins",
  "C   Padding",
  "C   Height/Width",
  "C   Box Model",
  "C   Outline",
  "C   Text",
  "C   Fonts",
  "C   Icons",
  "C   Links",
  "C   Lists",
  "C   Tables",
  "C   Display",
  "C   Max-width",
  "C Position",
  "C   Z-index",
  "C   Overflow",
  "C  Float",
  "C   Inline-block",
  "C   Align",
  "C   Combinators",
  "C   Pseudo-class",
  "C   Pseudo-element",
  "C   Opacity",
  "C   Navigation Bar",
  "C   Dropdowns",
  "C   Image Gallery",
  "C   Image Sprites",
  "C   Attr Selectors",
  "C   Forms",
  "C  Counters",
  "C   Website Layout",
  "C Units",
  "C   Specificity",
  "C   !important",
  "C   Math Functions",
];

export const cleftsidebaritems2 = [
  "C Border Images",
  "CBackgrounds",
  "C Colors",
  "CColor Keywords",
  "CGradients",
  "CShadows",
  "CText Effects",
  "CWeb Fonts",
  "C2D Transforms",
  "C3D Transforms",
  "CTransitions",
  "CRounded Corners",
  "C Animations",
  "C Tooltips",
  "CStyle Images",
  "C Image Reflection",
  "C object-fit",
  "C object-position",
  "C Masking",
  "C Buttons",
  "C Pagination",
  "C Multiple Columns",
  "C User Interface",
  "CVariables",
  "CBox Sizing",
  "CMedia Queries",
  "JAVA MQ Examples",
  "C Flexbox",
];

export const cleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "C Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "C SASS",
  "C Tutorial",
  "CExamples",
  "CTemplates",
  "CExamples",
  "CEditor",
  "C Snippets",
  "CQuiz",
  "C Exercises",
  "C Bootcamp",
  "C Certificate",
  "C References",
  "C Reference",
  "C Selectors",
  "C Functions",
  "C Reference Aural",
  "CWeb Safe Fonts",
  "CAnimatable",
  "C Units",
  "CPX-EM Converter",
  "C Colors",
  "JCColor Values",
  "C Default Values",
  "C Browser Support",
];

export const creferences = [
  "C Properties",
  "C Selectors",
  "C Browser Support",
  "CFunctions",
  "CAnimatable",
  "C Aural",
  "C Web Safe Fonts",
  "C Units",
  "C Colors",
  "CDefault Values",
  "C Entities",
];




export const cplusleftsidebaritems1 = [
  "C++   HOME",
  "C++   Introduction",
  "C++   Syntax",
  "C++   Selectors",
  "C++  How To",
  "C++  Comments",
  "C++   Colors",
  "C++   Backgrounds",
  "C++   Borders",
  "C++   Margins",
  "C++   Padding",
  "C++   Height/Width",
  "C++   Box Model",
  "C++   Outline",
  "C++   Text",
  "C++   Fonts",
  "C++   Icons",
  "C++   Links",
  "C++   Lists",
  "C++   Tables",
  "C++   Display",
  "C++   Max-width",
  "C++  Position",
  "C++  Z-index",
  "C++   Overflow",
  "C++   Float",
  "C++  Inline-block",
  "C++  Align",
  "C++   Combinators",
  "C++  Pseudo-class",
  "C++   Pseudo-element",
  "C++   Opacity",
  "C++   Navigation Bar",
  "C++  Dropdowns",
"C++   Image Gallery",
  "C++  Image Sprites",
  "C++  Attr Selectors",
  "C++  Forms",
  "C++  Counters",
  "C++   Website Layout",
  "C++  Units",
  "C++  Specificity",
  "C++  !important",
  "C++  Math Functions",
];

export const cplusleftsidebaritems2 = [
  "C++  Border Images",
  "C++ Backgrounds",
  "C++  Colors",
  "C++ Color Keywords",
  "C++ Gradients",
  "C++ Shadows",
  "C++ Text Effects",
  "C++ Web Fonts",
  "C++ 2D Transforms",
  "C++ 3D Transforms",
  "C++ Transitions",
  "C++ Rounded Corners",
  "C++  Animations",
  "C++  Tooltips",
  "C++ Style Images",
  "C++  Image Reflection",
  "C++  object-fit",
  "C++  object-position",
  "C++  Masking",
  "C++  Buttons",
  "C++  Pagination",
  "C++  Multiple Columns",
  "C++  User Interface",
  "C++ Variables",
  "C++ Box Sizing",
  "C++ Media Queries",
  "JAVA MQ Examples",
  "C++  Flexbox",
];

export const cplusleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "C++ Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "C++ SASS",
  "C++ Tutorial",
  "C++Examples",
  "C++Templates",
  "C++Examples",
  "C++Editor",
  "C++ Snippets",
  "C++Quiz",
  "C++ Exercises",
  "C++ Bootcamp",
  "C++ Certificate",
  "C++ References",
  "C++ Reference",
  "C++ Selectors",
  "C++ Functions",
  "C++ Reference Aural",
  "C++Web Safe Fonts",
  "C++Animatable",
  "C++ Units",
  "C++PX-EM Converter",
  "C++ Colors",
  "JCColor Values",
  "C++ Default Values",
  "C++Browser Support",
];

export const cplusreferences = [
  "C++ Properties",
  "C++ Selectors",
  "C++ Browser Support",
  "C++Functions",
  "C++Animatable",
  "C++ Aural",
  "C++ Web Safe Fonts",
  "C++ Units",
  "C++ Colors",
  "C++Default Values",
  "C++ Entities",
];






export const chashleftsidebaritems1 = [
  "C#  HOME",
  "C#  Introduction",
  "C#  Syntax",
  "C#  Selectors",
  "C# How To",
  "C# Comments",
  "C# Colors",
  "C#  Backgrounds",
  "C#  Borders",
  "C#  Margins",
  "C#  Padding",
  "C# Height/Width",
  "C#  Box Model",
  "C#  Outline",
  "C# Text",
  "C# Fonts",
  "C# Icons",
  "C# Links",
  "C#  Lists",
  "C# Tables",
  "C#  Display",
  "C# Max-width",
  "C# Position",
  "C#  Z-index",
  "C#  Overflow",
  "C#  Float",
  "C#  Inline-block",
  "C#  Align",
  "C#  Combinators",
  "C#  Pseudo-class",
  "C#  Pseudo-element",
  "C# Opacity",
  "C#  Navigation Bar",
  "C#  Dropdowns",
  "C#  Image Gallery",
  "C#  Image Sprites",
  "C#  Attr Selectors",
  "C# Forms",
  "C# Counters",
  "C# Website Layout",
  "JAVA  Units",
  "C#  Specificity",
  "C#  !important",
  "C# Math Functions",
];

export const chashleftsidebaritems2 = [
  "C#  Border Images",
  "C# Backgrounds",
  "C#  Colors",
  "C# Color Keywords",
  "C# Gradients",
  "C# Shadows",
  "C# Text Effects",
  "C# Web Fonts",
  "C# 2D Transforms",
  "C# 3D Transforms",
  "C# Transitions",
  "C# Rounded Corners",
  "C#  Animations",
  "C#  Tooltips",
  "C# Style Images",
  "C#  Image Reflection",
  "C#  object-fit",
  "C#  object-position",
  "C#  Masking",
  "C#  Buttons",
  "C#  Pagination",
  "C#  Multiple Columns",
  "C#  User Interface",
  "C# Variables",
  "C# Box Sizing",
  "C# Media Queries",
  "JAVA MQ Examples",
  "C#  Flexbox",
];

export const chashleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "C# Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "C# SASS",
  "C# Tutorial",
  "C#Examples",
  "C#Templates",
  "C#Examples",
  "C#Editor",
  "C# Snippets",
  "C#Quiz",
  "C# Exercises",
  "C# Bootcamp",
  "C# Certificate",
  "C# References",
  "C# Reference",
  "C# Selectors",
  "C# Functions",
  "C# Reference Aural",
  "C#Web Safe Fonts",
  "C#Animatable",
  "C# Units",
  "C#PX-EM Converter",
  "C# Colors",
  "JCColor Values",
  "C# Default Values",
  "C# Browser Support",
];

export const chashreferences = [
  "C# Properties",
  "C# Selectors",
  "C# Browser Support",
  "C#Functions",
  "C#Animatable",
  "C# Aural",
  "C# Web Safe Fonts",
  "CGitG#Units",
  "C# Colors",
  "C#Default Values",
  "C# Entities",
];



export const bootstrapleftsidebaritems1 = [
  "BOOTSTRAP HOME",
  "BOOTSTRAP Introduction",
  "BOOTSTRAP Syntax",
  "BOOTSTRAP Selectors",
  "BOOTSTRAPHow To",
  "BOOTSTRAP Comments",
  "BOOTSTRAP Colors",
  "BOOTSTRAP Backgrounds",
  "BOOTSTRAP Borders",
  "BOOTSTRAP Margins",
  "BOOTSTRAP Padding",
  "BOOTSTRAP Height/Width",
  "BOOTSTRAP Box Model",
  "BOOTSTRAP Outline",
  "BOOTSTRAP Text",
  "BOOTSTRAP Fonts",
  "BOOTSTRAP Icons",
  "BOOTSTRAP Links",
  "BOOTSTRAP Lists",
  "BOOTSTRAP Tables",
  "BOOTSTRAP  Display",
  "BOOTSTRAP Max-width",
  "BOOTSTRAP Position",
  "BOOTSTRAP Z-index",
  "BOOTSTRAP Overflow",
  "BOOTSTRAP Float",
  "BOOTSTRAP Inline-block",
  "BOOTSTRAP Align",
  "BOOTSTRAP Combinators",
  "BOOTSTRAP Pseudo-class",
  "BOOTSTRAP Pseudo-element",
  "BOOTSTRAP Opacity",
  "BOOTSTRAP  Navigation Bar",
  "BOOTSTRAP  Dropdowns",
  "BOOTSTRAP Image Gallery",
  "BOOTSTRAP  Image Sprites",
  "BOOTSTRAP  Attr Selectors",
  "BOOTSTRAP Forms",
  "BOOTSTRAP Counters",
  "BOOTSTRAP  Website Layout",
  "BOOTSTRAP  Units",
  "BOOTSTRAP  Specificity",
  "BOOTSTRAP  !important",
  "BOOTSTRAP  Math Functions",
];

export const bootstrapleftsidebaritems2 = [
  "BOOTSTRAP  Border Images",
  "BOOTSTRAP Backgrounds",
  "BOOTSTRAP  Colors",
  "BOOTSTRAP Color Keywords",
  "BOOTSTRAP Gradients",
  "BOOTSTRAP Shadows",
  "BOOTSTRAP Text Effects",
  "BOOTSTRAP Web Fonts",
  "BOOTSTRAP 2D Transforms",
  "BOOTSTRAP 3D Transforms",
  "BOOTSTRAP Transitions",
  "BOOTSTRAP Rounded Corners",
  "BOOTSTRAP  Animations",
  "BOOTSTRAP  Tooltips",
  "BOOTSTRAP Style Images",
  "BOOTSTRAP  Image Reflection",
  "BOOTSTRAP  object-fit",
  "BOOTSTRAP object-position",
  "BOOTSTRAP Masking",
  "BOOTSTRAP Buttons",
  "BOOTSTRAP Pagination",
  "BOOTSTRAP  Multiple Columns",
  "BOOTSTRAP  User Interface",
  "BOOTSTRAP Variables",
  "BOOTSTRAP Box Sizing",
  "BOOTSTRAP Media Queries",
  "BOOTSTRAP MQ Examples",
  "BOOTSTRAP  Flexbox",
];

export const bootstrapleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "BOOTSTRAP Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "BOOTSTRAP SASS",
  "BOOTSTRAP Tutorial",
  "BOOTSTRAP Examples",
  "BOOTSTRAP Templates",
  "BOOTSTRAP Examples",
  "BOOTSTRAP Editor",
  "BOOTSTRAP  Snippets",
  "BOOTSTRAP Quiz",
  "BOOTSTRAP  Exercises",
  "BOOTSTRAP Bootcamp",
  "BOOTSTRAP  Certificate",
  "BOOTSTRAP  References",
  "BOOTSTRAP  Reference",
  "BOOTSTRAP  Selectors",
  "BOOTSTRAP  Functions",
  "BOOTSTRAP  Reference Aural",
  "BOOTSTRAP Web Safe Fonts",
  "BOOTSTRAP Animatable",
  "BOOTSTRAP  Units",
  "BOOTSTRAP  Colors",
  "JCColor Values",
  "BOOTSTRAP  Default Values",
  "BOOTSTRAP  Browser Support",
];

export const bootstrapreferences = [
  "BOOTSTRAP  Properties",
  "BOOTSTRAP  Selectors",
  "BOOTSTRAP  Browser Support",
  "BOOTSTRAP Functions",
  "BOOTSTRAP Animatable",
  "BOOTSTRAP  Aural",
  "BOOTSTRAP  Web Safe Fonts",
  "BOOTSTRAP  Units",
  "BOOTSTRAP  Colors",
  "BOOTSTRAP Default Values",
  "BOOTSTRAP  Entities",
];



export const reactleftsidebaritems1 = [
  "REACT   HOME",
  "REACT  Introduction",
  "REACT  Syntax",
  "REACT   Selectors",
  "REACT How To",
  "REACT Comments",
  "REACT  Colors",
  "REACT  Backgrounds",
  "REACT   Borders",
  "REACT   Margins",
  "REACT   Padding",
  "REACT   Height/Width",
  "REACT   Box Model",
  "REACT  Outline",
  "REACT  Text",
  "REACT  Fonts",
  "REACT  Icons",
  "REACT  Links",
  "REACT  Lists",
  "REACT  Tables",
  "REACT  Display",
  "REACT  Max-width",
  "REACT  Position",
  "REACT  Z-index",
  "REACT  Overflow",
  "REACT Float",
  "REACT  Inline-block",
  "REACT  Align",
  "REACT  Combinators",
  "REACT  Pseudo-class",
  "REACT  Pseudo-element",
  "REACT  Opacity",
  "REACT  Navigation Bar",
  "REACT  Dropdowns",
  "REACT  Image Gallery",
  "REACT  Image Sprites",
  "REACT  Attr Selectors",
  "REACT  Forms",
  "REACT  Counters",
  "REACT  Website Layout",
  "REACT  Units",
  "REACT Specificity",
  "REACT !important",
  "RREACT  Border Images",
  "REACT Math Functions",
];

export const reactleftsidebaritems2 = [
  "REACT Backgrounds",
  "REACT  Colors",
  "REACT Color Keywords",
  "REACT Gradients",
  "REACT Shadows",
  "REACT Text Effects",
  "REACT Web Fonts",
  "REACT 2D Transforms",
  "REACT 3D Transforms",
  "REACT Transitions",
  "REACT Rounded Corners",
  "REACT Animations",
  "REACT Tooltips",
  "REACT Style Images",
  "REACT Image Reflection",
  "REACT object-fit",
  "REACT object-position",
  "REACT Masking",
  "REACT Buttons",
  "REACT  Pagination",
  "REACT  Multiple Columns",
  "REACT  User Interface",
  "REACT Variables",
  "REACT Box Sizing",
  "REACT Media Queries",
  "JAVAREACT MQ Examples",
  "REACT Flexbox", 
];

export const reactleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "REACT Examples",
  "REACT Snippets",
  "REACT Tutorial",
  "REACT Exercises",
  "REACT Examples",
  "REACT Certificate",
  "REACT Templates",
  "REACT Reference",
  "Editor",
  "REACT Functions",
  "REACT Quiz",
  "REACT Web Safe Fonts",
  "REACT Bootcamp",
  "REACT  Units",
  " REACT References",
  "REACT  Colors",
  "REACT Selectors",
  "REACT Reference Aural",
  "REACT  Browser Support",
  "REACT Animatable",
  "CPX-EM Converter",
  "JCColor Values",
  "REACT Default Values",
];

export const reactreferences = [
  "REACT  Properties",
  "REACT  Selectors",
  "REACT Browser Support",
  "REACT Functions",
  "REACT Animatable",
  "REACT  Aural",
  "REACT  Web Safe Fonts",
  "REACT Units",
  "REACT Colors",
  "REACT Default Values",
  "REACT  Entities",
];




export const mysqlleftsidebaritems1 = [
  "MYSQL  HOME",
  "MYSQL Introduction",
  "MYSQL Syntax",
  "MYSQL  Selectors",
  "MYSQLHow To",
  "MYSQLComments",
  "RMYSQLColors",
  "RMYSQLBackgrounds",
  "RMYSQL Borders",
  "MYSQL  Margins",
  "MYSQL  Padding",
  "MYSQL  Height/Width",
  "MYSQL  Box Model",
  "MYSQL Outline",
  "MYSQL  Text",
  "MYSQL  Fonts",
  "MYSQL  Icons",
  "MYSQL  Links",
  "MYSQL Lists",
  "MYSQL Tables",
  "MYSQL Display",
  "MYSQL Max-width",
  "MYSQL Position",
  "MYSQL Z-index",
  "MYSQL  Overflow",
  "MYSQL Float",
  "MYSQL  Inline-block",
  "MYSQL  Align",
  "MYSQL  Combinators",
  "MYSQL  Pseudo-class",
  "MYSQL Pseudo-element",
  "MYSQL  Opacity",
  "MYSQL  Navigation Bar",
  "MYSQL  Dropdowns",
  "MYSQL  Image Gallery",
  "MYSQL  Image Sprites",
  "MYSQL  Attr Selectors",
  "MYSQL  Forms",
  "MYSQL  Counters",
  "MYSQL  Website Layout",
  "MYSQL  Units",
  "MYSQLSpecificity",
  "MYSQL!important",
  "RREACT  Border Images",
  "MYSQL Math Functions",
];

export const mysqlleftsidebaritems2 = [
  "MYSQLBackgrounds",
  "MYSQL Colors",
  "MYSQLColor Keywords",
  "MYSQLGradients",
  "MYSQLShadows",
  "MYSQLText Effects",
  "MYSQLWeb Fonts",
  "MYSQL 2D Transforms",
  "MYSQL 3D Transforms",
  "MYSQL Transitions",
  "MYSQL Rounded Corners",
  "MYSQL Animations",
  "MYSQL Tooltips",
  "MYSQL Style Images",
  "MYSQL Image Reflection",
  "MYSQL object-fit",
  "MYSQLobject-position",
  "MYSQLMasking",
  "MYSQL Buttons",
  "MYSQL  Pagination",
  "MYSQL  Multiple Columns",
  "MYSQL User Interface",
  "MYSQL Variables",
  "MYSQL Box Sizing",
  "MYSQL Media Queries",
  "JAVAREACT MQ Examples",
  "MYSQL Flexbox", 
];

export const mysqlleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "MYSQL Examples",
  "MYSQL Snippets",
  "MYSQL Tutorial",
  "MYSQLExercises",
  "MYSQL Examples",
  "MYSQL Certificate",
  "MYSQL Templates",
  "MYSQL Reference",
  "Editor",
  "MYSQL Functions",
  "MYSQL Quiz",
  "MYSQL Web Safe Fonts",
  "MYSQL Bootcamp",
  "MYSQL  Units",
  "MYSQL References",
  "MYSQL  Colors",
  "MYSQL Selectors",
  "MYSQLReference Aural",
  "MYSQL  Browser Support",
  "MYSQL Animatable",
  "CPX-EM Converter",
  "JCColor Values",
  "MYSQL Default Values",
];

export const mysqlreferences = [
  "MYSQL  Properties",
  "MYSQL  Selectors",
  "MYSQLBrowser Support",
  "MYSQL Functions",
  "MYSQL Animatable",
  "MYSQL Aural",
  "MYSQL Web Safe Fonts",
  "MYSQL Units",
  "MYSQL Colors",
  "MYSQL Default Values",
  "MYSQL  Entities",
];




export const gitleftsidebaritems1 = [
  "GIT   HOME",
  "GIT  Introduction",
  "GIT  Syntax",
  "GIT   Selectors",
  "GIT How To",
  "GIT Comments",
  "GIT  Colors",
  "GIT  Backgrounds",
  "GIT   Borders",
  "GIT   Margins",
  "GIT   Padding",
  "GIT   Height/Width",
  "GIT   Box Model",
  "GIT  Outline",
  "GIT  Text",
  "GIT  Fonts",
  "GIT  Icons",
  "GIT  Links",
  "GIT  Lists",
  "GIT  Tables",
  "GIT  Display",
  "GIT  Max-width",
  "GIT  Position",
  "GIT  Z-index",
  "GIT  Overflow",
  "GIT Float",
  "GIT  Inline-block",
  "GIT  Align",
  "GIT  Combinators",
  "GIT  Pseudo-class",
  "GIT  Pseudo-element",
  "GIT  Opacity",
  "GIT  Navigation Bar",
  "GIT  Dropdowns",
  "GIT  Image Gallery",
  "GIT  Image Sprites",
  "GIT  Attr Selectors",
  "GIT  Forms",
  "GIT  Counters",
  "GIT  Website Layout",
  "GIT  Units",
  "GIT Specificity",
  "GIT !important",
  "RGIT  Border Images",
  "RGITMath Functions",
];

export const gitleftsidebaritems2 = [
  "GIT Backgrounds",
  "GIT  Colors",
  "GIT Color Keywords",
  "GIT Gradients",
  "GIT Shadows",
  "GIT Text Effects",
  "GIT Web Fonts",
  "GIT 2D Transforms",
  "GIT 3D Transforms",
  "GIT Transitions",
  "GIT Rounded Corners",
  "GIT Animations",
  "GIT Tooltips",
  "GITStyle Images",
  "GIT Image Reflection",
  "GIT object-fit",
  "GIT object-position",
  "GIT Masking",
  "GIT Buttons",
  "GIT  Pagination",
  "GIT  Multiple Columns",
  "GIT  User Interface",
  "GIT Variables",
  "GIT Box Sizing",
  "GIT Media Queries",
  "JAVAREACT MQ Examples",
  "GIT Flexbox", 
];

export const gitleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "GIT Examples",
  "GIT Snippets",
  "GIT Tutorial",
  "GIT Exercises",
  "GIT Examples",
  "GIT Certificate",
  "GIT Templates",
  "GIT Reference",
  "Editor",
  "GIT Functions",
  "GIT Quiz",
  "GITWeb Safe Fonts",
  "GITBootcamp",
  "GIT  Units",
  "GIT References",
  "GIT  Colors",
  "GIT Selectors",
  "GIT Reference Aural",
  "GIT  Browser Support",
  "GIT Animatable",
  "CPX-EM Converter",
  "JCColor Values",
  "GIT Default Values",
];

export const gitreferences = [
  "GIT  Properties",
  "GIT  Selectors",
  "GIT Browser Support",
  "GIT Functions",
  "GIT Animatable",
  "GIT  Aural",
  "GIT  Web Safe Fonts",
  "GIT Units",
  "GIT Colors",
  "GIT Default Values",
  "GIT  Entities",
];



export const nodejsleftsidebaritems1 = [
  "NODEJS    HOME",
  "NODEJS   Introduction",
  "NODEJS   Syntax",
  "NODEJS    Selectors",
  "NODEJS  How To",
  "NODEJS  Comments",
  "NODEJS   Colors",
  "NODEJS  Backgrounds",
  "NODEJS   Borders",
  "NODEJS    Margins",
  "NODEJS   Padding",
  "NODEJS   Height/Width",
  "NODEJS   Box Model",
  "NODEJS  Outline",
  "NODEJS  Text",
  "NODEJS  Fonts",
  "NODEJS  Icons",
  "NODEJS  Links",
  "RNODEJS Lists",
  "NODEJS   Tables",
  "NODEJS   Display",
  "NODEJS  Max-width",
  "NODEJS  Position",
  "NODEJS  Z-index",
  "NODEJS  Overflow",
  "NODEJS Float",
  "NODEJS  Inline-block",
  "RNODEJS Align",
  "NODEJS  Combinators",
  "NODEJS  Pseudo-class",
  "NODEJS  Pseudo-element",
  "NODEJS  Opacity",
  "NODEJS  Navigation Bar",
  "NODEJS  Dropdowns",
  "NODEJS  Image Gallery",
  "NODEJS  Image Sprites",
  "NODEJS  Attr Selectors",
  "NODEJS  Forms",
  "NODEJS  Counters",
  "NODEJS  Website Layout",
  "NODEJS  Units",
  "NODEJS Specificity",
  "NODEJS !important",
  "NODEJS   Border Images",
  "NODEJS  Math Functions",
];

export const nodejsleftsidebaritems2 = [
  "NODEJS Backgrounds",
  "NODEJS Colors",
  "NODEJS Color Keywords",
  "NODEJS Gradients",
  "NODEJS Shadows",
  "NODEJSText Effects",
  "NODEJS Web Fonts",
  "NODEJS 2D Transforms",
  "NODEJS 3D Transforms",
  "NODEJS Transitions",
  "NODEJS Rounded Corners",
  "NODEJS Animations",
  "NODEJS Tooltips",
  "NODEJS Style Images",
  "NODEJS Image Reflection",
  "NODEJS object-fit",
  "NODEJS object-position",
  "NODEJS Masking",
  "NODEJS Buttons",
  "NODEJS  Pagination",
  "NODEJS  Multiple Columns",
  "NODEJS  User Interface",
  "NODEJS Variables",
  "NODEJS Box Sizing",
  "NODEJS Media Queries",
  "JAVAREACT MQ Examples",
  "NODEJSFlexbox", 
];

export const nodejsleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "NODEJS Examples",
  "NODEJS Snippets",
  "NODEJS Tutorial",
  "NODEJS  Exercises",
  "NODEJS Examples",
  "NODEJS Certificate",
  "NODEJS  Templates",
  "NODEJS Reference",
  "Editor",
  "NODEJS  Functions",
  "NODEJS Quiz",
  "NODEJS Web Safe Fonts",
  "NODEJS  Bootcamp",
  "NODEJS  Units",
  " NODEJS References",
  "NODEJS  Colors",
  "NODEJS Selectors",
  "NODEJS Reference Aural",
  "NODEJS  Browser Support",
  "NODEJS Animatable",
  "CPX-EM Converter",
  "JCColor Values",
  "NODEJS  Default Values",
];

export const nodejsreferences = [
  "NODEJS Properties",
  "NODEJS Selectors",
  "NODEJSBrowser Support",
  "NODEJSFunctions",
  "NODEJSAnimatable",
  "NODEJS Aural",
  "NODEJS Web Safe Fonts",
  "NODEJSUnits",
  "NODEJSColors",
  "NODEJSDefault Values",
  "NODEJS Entitie",
];

export const phpleftsidebaritems1 = [
  "PHP   HOME",
  "PHP Introduction",
  "PHP Syntax",
  "PHP  Selectors",
  "PHPHow To",
  "PHPComments",
  "PHP Colors",
  "PHP Backgrounds",
  "PHP  Borders",
  "PHP  Margins",
  "PHP  Padding",
  "PHP  Height/Width",
  "PHP  Box Model",
  "PHP Outline",
  "PHP Text",
  "PHP Fonts",
  "PHP Icons",
  "PHP Links",
  "PHP Lists",
  "PHP Tables",
  "PHP Display",
  "PHP Max-width",
  "RPHPPosition",
  "PHP Z-index",
  "REACT  Overflow",
  "PHPFloat",
  "PHP Inline-block",
 " PHP  Align",
  "PHP  Combinators",
  "PHP  Pseudo-class",
  "PHP  Pseudo-element",
  "PHP  Opacity",
  "PHP Navigation Bar",
  "PHP Dropdowns",
  "PHP Image Gallery",
  "PHP Image Sprites",
  "PHP Attr Selectors",
  "PHP Forms",
  "PHP Counters",
  "PHP Website Layout",
  "PHP Units",
  "PHPSpecificity",
"PHP !important",
  "PHP  Border Images",
  "PHP Math Functions",
];

export const phpleftsidebaritems2 = [
  "PHP Backgrounds",
  "PHP Colors",
  "PHPColor Keywords",
  "PHP Gradients",
  "PHP Shadows",
  "PHPText Effects",
  "PHPWeb Fonts",
  "PHP2D Transforms",
  "PHP3D Transforms",
  "PHPTransitions",
  "PHPRounded Corners",
  "PHPAnimations",
  "PHPTooltips",
  "PHPStyle Images",
  "PHPImage Reflection",
  "PHP object-fit",
  "PHP object-position",
  "PHP Masking",
  "PHP Buttons",
  "PHP  Pagination",
  "PHP  Multiple Columns",
  "PHP  User Interface",
  "PHP Variables",
  "PHP Box Sizing",
  "PHP Media Queries",
  "PHP Flexbox", 
];

export const phpleftsidebaritems3 = [
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "PHP Examples",
  "PHP Snippets",
  "RPHPTutorial",
  "PHP Exercises",
  "PHP Examples",
  "PHP Certificate",
  "PHP Templates",
  "PHP Reference",
  "Editor",
  "PHP Functions",
  "PHP Quiz",
  "PHP Web Safe Fonts",
  "PHP Bootcamp",
  "PHP  Units",
  "PHP References",
  "PHP  Colors",
  "PHP Selectors",
  "PHP Reference Aural",
  "PHP  Browser Support",
  "PHP Animatable",
  "CPX-EM Converter",
  "JCColor Values",
  "RPHPDefault Values",
];

export const phpreferences = [
  "PHP  Properties",
  "PHP  Selectors",
  "PHP Browser Support",
  "PHP FunctionsPHPPHP Animatable",
  "PHP Aural",
  "PHP Web Safe Fonts",
  "PHPUnits",
  "PHPColors",
  "PHPDefault Values",
  "PHP Entities",
];
